class PakistanLocations {
  PakistanLocations._(); // private constructor - prevents instantiation

  static final Map<String, List<String>> provincesCities = {
    "Punjab": [
      "Lahore",
      "Faisalabad",
      "Rawalpindi",
      "Multan",
      "Gujranwala",
      "Sialkot",
      "Bahawalpur",
      "Sargodha",
      "Sahiwal",
      "Sheikhupura",
      "Jhang",
      "Rahim Yar Khan",
      "Gujrat",
      "Kasur",
      "Okara",
      "Dera Ghazi Khan",
      "Chiniot",
      "Wah Cantonment",
      "Mandi Bahauddin",
      "Attock",
      "Vehari",
      "Muzaffargarh",
      "Bahawalnagar",
      "Nankana Sahib",
      "Toba Tek Singh",
      "Jhelum",
      "Khanewal",
      "Hafizabad",
      "Layyah",
      "Pakpattan",
      "Chakwal",
      "Narowal",
      "Lodhran",
      "Khushab",
      "Mianwali",
      "Bhakkar",
      "Rajanpur",
      "Kot Addu",
    ],
    "Sindh": [
      "Karachi",
      "Hyderabad",
      "Sukkur",
      "Larkana",
      "Nawabshah",
      "Mirpur Khas",
      "Jacobabad",
      "Shikarpur",
      "Khairpur",
      "Dadu",
      "Thatta",
      "Badin",
      "Sanghar",
      "Tando Adam",
      "Tando Allahyar",
      "Ghotki",
      "Kashmore",
      "Umerkot",
      "Matiari",
      "Jamshoro",
      "Kambar",
      "Naushahro Feroze",
      "Shaheed Benazirabad",
      "Sujawal",
      "Tharparkar",
    ],
    "Khyber Pakhtunkhwa": [
      "Peshawar",
      "Mardan",
      "Abbottabad",
      "Swat (Mingora)",
      "Kohat",
      "Bannu",
      "Dera Ismail Khan",
      "Mansehra",
      "Charsadda",
      "Nowshera",
      "Swabi",
      "Haripur",
      "Chitral",
      "Batagram",
      "Buner",
      "Hangu",
      "Karak",
      "Lakki Marwat",
      "Malakand",
      "Shangla",
      "Tank",
      "Torghar",
      "Upper Dir",
      "Lower Dir",
      "Kohistan",
    ],
    "Balochistan": [
      "Quetta",
      "Gwadar",
      "Turbat",
      "Khuzdar",
      "Sibi",
      "Chaman",
      "Zhob",
      "Loralai",
      "Dera Bugti",
      "Nasirabad",
      "Kalat",
      "Mastung",
      "Pishin",
      "Panjgur",
      "Kharan",
      "Lasbela (Uthal)",
      "Jaffarabad",
      "Killa Saifullah",
      "Killa Abdullah",
      "Musakhel",
      "Barkhan",
      "Awaran",
      "Washuk",
      "Ziarat",
    ],
    "Gilgit-Baltistan": [
      "Gilgit",
      "Skardu",
      "Hunza",
      "Nagar",
      "Ghanche",
      "Ghizer",
      "Astore",
      "Diamer",
      "Shigar",
      "Kharmang",
    ],
    "Azad Kashmir": [
      "Muzaffarabad",
      "Mirpur",
      "Rawalakot",
      "Kotli",
      "Bhimber",
      "Bagh",
      "Neelum",
      "Hattian Bala",
      "Sudhnoti (Pallandri)",
      "Haveli",
    ],
    "Islamabad Capital Territory": ["Islamabad"],
  };

  // Convenience getter if you just need province names somewhere
  static List<String> get provinces => provincesCities.keys.toList();

  // Convenience method to get cities for a given province safely
  static List<String> citiesFor(String? province) {
    if (province == null) return [];
    return provincesCities[province] ?? [];
  }
}
